### PR TITLE
Organize project

### PR DESCRIPTION
**Pull request by davidyee**

### CODE REVIEW

**Comment by arbitraryconstants** [comment]
* If you log in as a user that doesn’t exist the app crashes.



* When you log into your newly activated account you immediately get an error as it takes you to http://127.0.0.1:8000/app. Though, if you change the url to http://127.0.0.1:8000/ this works fine. 
screen shot 2017-03-18 at 1 44 23 pm

* From http://127.0.0.1:8000/authors/  if you click on an author you get an error when you try to view that author’s page: http://127.0.0.1:8000/authors/5ec32f5e-8e5e-495f-b38e-3cf340d18b2c
screen shot 2017-03-18 at 2 13 38 pm

**Comment by davidyee** [comment]
@arbitraryconstants I fixed the bugs you reported but I could not reproduce the first bug you mentioned relating to logging in with a user that does not exist.

**Comment by adamjford** [comment]
Yeah, neither can I.

**Comment by arbitraryconstants** [comment]
I can't reproduce the first bug I mentioned either... so I guess either it's fixed or it never was...

**Review by arbitraryconstants — APPROVED** [review]
Looks good!

**Pull request merged**
