### PR TITLE
Add custom user registration and edit profile page

### PR DESCRIPTION
**Pull request by davidyee**

### CODE REVIEW

**Review by ookmm — COMMENTED** [review]
I noticed that we were kind of working on the same files at the same time, more importantly navigations/main.html and landing/index.html. Do you care at all that I push and merge mine first and you can add your changes to them. Thanks.

**Review by arbitraryconstants — APPROVED** [review]
Everything seems to work, code looks fine. The only thing I think should be changed is that when the user edits their profile and clicks the "Save" button it would be ideal if they were taken back to http://localhost:8000/post/ rather than staying on the edit page. That way it would be more clear that the entered data had been saved.

**Comment by ookmm** [comment]
There are some changes that I would like to discuss before the merge.

**Review by ookmm — CHANGES_REQUESTED** [review]
We can discuss it the lab.

**Review by ookmm — APPROVED** [review]

**Comment by ookmm** [comment]
It is all good now. Thanks.

**Pull request merged**
