### PR TITLE
29 Restrict other authors from modifying my data

### PR DESCRIPTION
**Pull request by davidyee**

### CODE REVIEW

**Comment by arbitraryconstants** [comment]
David, could you clarify what this user story does?
I'm not sure how to verify that it is working correctly. Is there a url I can go to test each possible error code template?

**Comment by davidyee** [comment]
This user story would encompass everything to do with user data. This user story would also extend to the posts feature as well. So the code in this PR only relates to the rules for restricting other authors from modifying my profile. @ookmm posts feature will need to be updated to fully fulfill this user story.

Great question! See the `dashboard/debug/urls.py` for some possible targets. For example: http://127.0.0.1:8000/debug/404

**Comment by arbitraryconstants** [comment]
Okay, thanks for explaining :)

**Comment by arbitraryconstants** [comment]
I know this one doesn't request my approval, but I approve!

**Review by arbitraryconstants — APPROVED** [review]
Tested this. Works as expected.

**Pull request merged**
