### PR TITLE
Add RESTful interface for User and Author models

### PR DESCRIPTION
**Pull request by davidyee**
To test, first login as a superuser and then visit this endpoint to see all the exposed models:
http://127.0.0.1:8000/service/

TODO: Expose specific, custom endpoints to authenticated server nodes as per the [example-article.json](https://github.com/abramhindle/CMPUT404-project-socialdistribution/blob/master/example-article.json).

### CODE REVIEW

**Review by arbitraryconstants — APPROVED** [review]
Tested this and it works as expected.

**Comment by arbitraryconstants** [comment]
Curious though, why is it necessary for us to differentiate between user and author? Would it make sense to have one model to represent both?

**Comment by davidyee** [comment]
@arbitraryconstants It's just so that we can utilize the Django User model without replacing it with a completely custom model of our own. Take a look at [this documentation](https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#extending-the-existing-user-model) for the rationale behind using a `OneToOneField` foreign key to the `User` model.

**Comment by arbitraryconstants** [comment]
Okay, thanks I will check out that link.

**Pull request merged**
